site_name: Drucker
docs_dir: docs

pages:
  - Home: index.md
  - Usage: usage.md
  - Features: features.md
  - Tools: tools.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition:

extra_css:
  - extra.css
