#!/bin/bash

if [$TRAVIS_PULL_REQUEST == "true"]; then
  echo "From PR, exiting"
  exit 0
fi

# enable error logging
set -e

rm -rf _site
mkdir _site

git clone https://${GH-TOKEN}@github.com/ovh-ux/drucker.git --branch gh-pages _site

bundle exec jekyll build

# push
cd _site
git config user.email "${GH-MAIL}"
git config user.name "${GH-USER}"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
