#!/bin/bash

if [$TRAVIS_PULL_REQUEST == "true"]; then
  echo "From PR, exiting"
  exit 0
fi

# enable error logging
set -e

echo "$GH_MAIL"
echo "$GH_USER"
echo "$GH_TOKEN"

rm -rf _site
mkdir _site

git clone https://${GH_TOKEN}@github.com/ovh-ux/drucker.git --branch gh-pages _site

bundle exec jekyll build

# push
cd _site
git config user.email "${GH_MAIL}"
git config user.name "${GH_USER}"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
