sass:
    sass_dir: _sass
    style: compressed

exclude:
- bin
- Gemfile
- Gemfile.lock
- Rakefile
- scripts
- README.md
- vendor
- node_modules/less-plugin-remcalc
- node_modules/ovh-ui-kit-bs/src
- node_modules/ovh-ui-kit-bs/bower.json
- node_modules/ovh-ui-kit-bs/index.html
- node_modules/ovh-ui-kit-bs/LICENSE
- node_modules/ovh-ui-kit-bs/package-lock.json
- node_modules/ovh-ui-kit-bs/package.json
- node_modules/ovh-ui-kit-bs/README.md
